version: 0.1
phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template-file template.json --s3-bucket {BUCKET_NAME}
                                   --output-template-file outputTemplate.yml
artifacts:
  type: zip
  files:
    - '**/*'

